sudo: true
language: node_js
node_js:
  - 16
cache: npm
branches:
  only:
    - master # build master branch only
script:
  - yarn install
  - wget https://github.com/jgm/pandoc/releases/download/2.11.4/pandoc-2.11.4-1-amd64.deb
  - sudo dpkg -i pandoc-2.11.4-1-amd64.deb
  - pandoc --version
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public